/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/beaker.glb --transform 
Files: public/models/beaker.glb [2.51MB] > D:\IbtikarZ\1Chemistry\1Chem\beaker-transformed.glb [94.72KB] (96%)
Author: itschemistry2 (https://sketchfab.com/itschemistry2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beaker-c1560b532f1d4f9f808f4963d6c877c8
Title: beaker
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Beaker(props) {
  const { nodes, materials } = useGLTF('/models/beaker-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} position={[0, 0.331, 0]} scale={2.95} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.004']} position={[0, 4.351, 3.515]} rotation={[Math.PI / 2, 0, 0]} scale={[2.868, 0.781, 3.122]} />
    </group>
  )
}

useGLTF.preload('/models/beaker-transformed.glb')
