/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/burner.glb --transform 
Files: public/models/burner.glb [1.79MB] > D:\IbtikarZ\1Chemistry\1Chem\burner-transformed.glb [130.74KB] (93%)
Author: Dreamsoft Innovations Private Limited (https://sketchfab.com/dreamsoftin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bunsen-burner-5185e41b2beb48fa8f15ca3707f43e10
Title: Bunsen Burner
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Burner(props) {
  const { nodes, materials } = useGLTF('/models/burner-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bunsen_Burner_Bunsen_Burner_Mat_0.geometry} material={materials.Bunsen_Burner_Mat} />
    </group>
  )
}

useGLTF.preload('/models/burner-transformed.glb')
