/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/flask.glb --transform 
Files: public/models/flask.glb [83.09KB] > D:\IbtikarZ\1Chemistry\1Chem\flask-transformed.glb [20.22KB] (76%)
Author: itschemistry2 (https://sketchfab.com/itschemistry2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/erlenmeyer-flask-e2ce2700c8a84ebcba6b0e20e477263c
Title: erlenmeyer flask
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Flask(props) {
  const { nodes, materials } = useGLTF('/models/flask-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} scale={6.637} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['582896-removebg-preview']} position={[0, 6.38, 6.08]} rotation={[Math.PI / 2, 0, 0]} scale={[6.755, 6.755, 9.376]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['8985874-removebg-preview']} position={[7.451, 4.799, 1.754]} rotation={[1.591, -0.115, -1.51]} scale={3.335} />
    </group>
  )
}

useGLTF.preload('/models/flask-transformed.glb')
