/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pipette.glb --transform 
Files: public/models/pipette.glb [1.15MB] > D:\IbtikarZ\1Chemistry\1Chem\pipette-transformed.glb [48.73KB] (96%)
Author: 3dLabWare (https://sketchfab.com/3dlabwaremodels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pipette-laboratory-essential-tool-4ed0651f9de14cdf96891449acb7cc38
Title: Pipette - Laboratory Essential Tool
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pipette-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pipette__0.geometry} material={materials['Scene_-_Root']} position={[0.05, 0, -0.09]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/pipette-transformed.glb')
