/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/table.glb --transform 
Files: public/models/table.glb [413.72KB] > D:\IbtikarZ\1Chemistry\1Chem\table-transformed.glb [40.1KB] (90%)
Author: GroundZer0 (https://sketchfab.com/GroundZer0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lab-table-wip-536386cf744c4bc5839a447bbc0a6937
Title: Lab table WIP
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Table(props) {
  const { nodes, materials } = useGLTF('/models/table-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.lambert1} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.blinn2} />
    </group>
  )
}

useGLTF.preload('/models/table-transformed.glb')
