/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/thermometer.glb --transform 
Files: public/models/thermometer.glb [285.56KB] > D:\IbtikarZ\1Chemistry\1Chem\thermometer-transformed.glb [40.55KB] (86%)
Author: BlackCube (https://sketchfab.com/blackcube4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fever-thermometer-acb2c16f9224404d996ab44c26d58176
Title: Fever thermometer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/thermometer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fever_thermometer_Main_0.geometry} material={materials.Main} position={[0, 0, -0.069]} scale={0.012} />
      <mesh geometry={nodes.fever_thermometer_Tip_0.geometry} material={materials.material} position={[0, 0, -0.069]} scale={0.012} />
      <mesh geometry={nodes.fever_thermometer_Glas_0.geometry} material={materials.Glas} position={[0, 0, -0.069]} scale={0.012} />
      <mesh geometry={nodes.fever_thermometer_Display_0.geometry} material={materials.Display} position={[0, 0, -0.069]} scale={0.012} />
    </group>
  )
}

useGLTF.preload('/thermometer-transformed.glb')
