/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tuberack.glb --transform 
Files: public/models/tuberack.glb [756.9KB] > D:\IbtikarZ\1Chemistry\1Chem\tuberack-transformed.glb [71.37KB] (91%)
Author: Kroko.blend (https://sketchfab.com/jaromir.ternavskiy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/test-tube-rack-ea40676ae43340a58b4f1cd44d5a1360
Title: Test Tube Rack
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tuberack-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-1.213, 2.755, 0.116]} />
      <mesh geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.001']} position={[0.557, 1.794, -1.905]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.884, 0.884, 1.71]} />
    </group>
  )
}

useGLTF.preload('/tuberack-transformed.glb')
